# Generated by Django 4.2.3 on 2024-08-04 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_category_post_notification_comment_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('Like', 'Like'), ('Comment', 'Comment')], max_length=100),
        ),
    ]
